### ISSUE TITLE
Todo: Easy improvements

### ISSUE THREAD

**Issue by David-Morales-Norato** [pycolibri/pycolibri#122]
- [ ] Add description to Github repository
- [ ] Add link in documentation to github repository
- [x] Spam social networks about Colibri
- [ ] Github tutorial to HDSP but contributing to pycolibri (We can list a wide range of easy to fix problems and in that tutorial we give the problems to the atendess to solve them, make the commits PR and aproove the changes by us.
