### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by David-Morales-Norato** [pycolibri/pycolibri#38]
### Tasks
- [x] #43
- [x] Make Stronger Dataloader. Load custom Dataset (ARAD)
- [x] dataset import is from colibri_hdsp.datasets.datasets import Dataset. Quite Ugly
- [x] The dataset is not normalized. We need to include a normalization preprocess in the Dataset object
