### ISSUE TITLE
TODO: Datasets

### ISSUE THREAD

**Issue by David-Morales-Norato** [pycolibri/pycolibri#44]
- [ ] Data augmentation
- [x] Generalize normalization of data
- [x] Generalize data lecture (custom dataset .mat)
- [x] Include unitary test for Datasets

```python
filenames = get_all_filenames(data_path.decode())

for filename in filenames:
    if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
        yield load_image(filename)

    if name == 'arad':
        yield load_arad_image(filename)

    else:
        raise "The filename type image is unknown, please check the data_path"
```

**Comment by Enmartz** [comment]
This issue has already been solved in #157, please close this.
